name: travelling_agency
recipe: symfony
config:
  webroot: public
services:
  database:
    type: mysql
    portforward: 3307
    creds: 
      user: rita
      password: admin
      database: voyages 